# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.api_key: 'B24151BAEC29DF305C63002E4B69A00D'
    app.secret_key: 'F1AA48CB4575A27B8EC62AF357EBCEA2'
    app.api_url: 'https://api-key.fusionbrain.ai/'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
#            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\Text2ImageService:
        arguments:
            $apiKey: '%app.api_key%'
            $secretKey: '%app.secret_key%'
            $apiUrl: '%app.api_url%'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\EventListener\AddCustomHeaderListener:
        tags:
            - {
                name: kernel.event_listener,
                event: kernel.response,
                method: "addHeader"
            }
